# .github/workflows/hello.yml

name: Hello GitHub Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository

      - name: print
        run: echo "hello git"
